version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: hospital_postgres
    environment:
      POSTGRES_DB: hospital_db
      POSTGRES_USER: hospital_user
      POSTGRES_PASSWORD: hospital_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: hospital_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  go_backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: "host=postgres user=hospital_user password=hospital_pass dbname=hospital_db port=5432 sslmode=disable"
      FIREBASE_ENABLED: "false"
      FIREBASE_PROJECT_ID: "hospital-app-e1548"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:

